---
- name: Deploy k3s {{ k3s_version }} binary for arch x64
  become: true
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/fetched/{{ k3s_version }}/k3s"
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: 0755
  when: ansible_facts.architecture == "x86_64"


- name: Create k3s container images drop directory
  become: true
  ansible.builtin.file:
    path: "/var/lib/rancher/k3s/agent/images/"
    state: directory
    owner: "root"
    group: "root"
    mode: 0755
  register: images_drop_dir

- name: Deploy k3s {{ k3s_version }} container images for arch x64
  become: true
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/fetched/{{ k3s_version }}/k3s-airgap-images-amd64.tar"
    dest: "{{ images_drop_dir.path }}"
    owner: root
    group: root
    mode: 0644
  when: ansible_facts.architecture == "x86_64"

- name: Deploy extra container images for arch x64
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ images_drop_dir.path }}"
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - "{{ playbook_dir }}/fetched/container_images/*.tar"
  when: ansible_facts.architecture == "x86_64"

# - name: Download k3s binary arm64
#   get_url:
#     url: https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/k3s-arm64
#     checksum: sha256:https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/sha256sum-arm64.txt
#     dest: /usr/local/bin/k3s
#     owner: root
#     group: root
#     mode: 0755
#   when:
#     - ( ansible_facts.architecture is search("arm") and
#         ansible_facts.userspace_bits == "64" ) or
#       ansible_facts.architecture is search("aarch64")

# - name: Download k3s binary armhf
#   get_url:
#     url: https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/k3s-armhf
#     checksum: sha256:https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/sha256sum-arm.txt
#     dest: /usr/local/bin/k3s
#     owner: root
#     group: root
#     mode: 0755
#   when:
#     - ansible_facts.architecture is search("arm")
#     - ansible_facts.userspace_bits == "32"
