---
- name: Retreive kubeconfig
  ansible.builtin.fetch:
    src: /etc/rancher/k3s/k3s.yaml 
    dest: "{{ kubeconfig }}"
    flat: yes

- name: Fix perm {{ kubeconfig }}
  ansible.builtin.file:
    path: "{{ kubeconfig }}"
    mode: '0600'
  delegate_to: localhost

- name: Reconfig
  ansible.builtin.replace:
    path: "{{ kubeconfig }}"
    regexp: '(    server: https:)\/\/127\.0\.0\.1\:(6443)?$'
    replace: \1//{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:\2
  delegate_to: localhost